# Generated by Django 5.0 on 2024-12-30 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts',
                'indexes': [models.Index(fields=['name'], name='contacts_name_084782_idx'), models.Index(fields=['phone_number'], name='contacts_phone_n_69cfc0_idx')],
                'unique_together': {('phone_number', 'added_by')},
            },
        ),
        migrations.CreateModel(
            name='SpamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('category', models.CharField(choices=[('unclassified', 'Unclassified'), ('fraud', 'Fraud'), ('telemarketer', 'Telemarketer')], default='unclassified', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spam_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spam_reports',
                'indexes': [models.Index(fields=['phone_number'], name='spam_report_phone_n_041c24_idx'), models.Index(fields=['category'], name='spam_report_categor_2c5729_idx')],
            },
        ),
    ]
